### ISSUE TITLE
(IMPORT FAILED): /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-SUPIR

### ISSUE THREAD

**Issue by Amit30swgoh** [kijai/ComfyUI-SUPIR#116]
![image](https://github.com/kijai/ComfyUI-SUPIR/assets/42430868/6495e9fd-46a2-4191-a63a-3e7159c71785)
![image](https://github.com/kijai/ComfyUI-SUPIR/assets/42430868/3a504748-8f0b-405e-b902-16e882b1796c)

**Comment by Amit30swgoh** [comment]
Tried fix: 

Install custom node 'ComfyUI-SUPIR'
Try fixing: ['https://github.com/kijai/ComfyUI-SUPIR']
Install: pip packages

## ComfyUI-Manager: EXECUTE => ['/usr/bin/python3', '-m', 'pip', 'install', 'transformers>=4.28.1']
                 
## ComfyUI-Manager: EXECUTE => ['/usr/bin/python3', '-m', 'pip', 'install', 'fsspec>=2023.4.0']
 
## ComfyUI-Manager: EXECUTE => ['/usr/bin/python3', '-m', 'pip', 'install', 'kornia>=0.6.9']
                         
## ComfyUI-Manager: EXECUTE => ['/usr/bin/python3', '-m', 'pip', 'install', 'open-clip-torch>=2.17.1']
                                         
## ComfyUI-Manager: EXECUTE => ['/usr/bin/python3', '-m', 'pip', 'install', 'Pillow>=9.4.0']
 
## ComfyUI-Manager: EXECUTE => ['/usr/bin/python3', '-m', 'pip', 'install', 'pytorch-lightning>=2.2.1']
 Collecting pytorch-lightning>=2.2.1
   Using cached pytorch_lightning-2.2.4-py3-none-any.whl (802 kB)
                                          Installing collected packages: pytorch-lightning
   Attempting uninstall: pytorch-lightning
     Found existing installation: pytorch-lightning 1.5.0
     Uninstalling pytorch-lightning-1.5.0:
       Successfully uninstalled pytorch-lightning-1.5.0
 Successfully installed pytorch-lightning-2.2.4

## ComfyUI-Manager: EXECUTE => ['/usr/bin/python3', '-m', 'pip', 'install', 'omegaconf']
   
## ComfyUI-Manager: EXECUTE => ['/usr/bin/python3', '-m', 'pip', 'install', 'accelerate']
                                   Attempt to fixing '['https://github.com/kijai/ComfyUI-SUPIR']' is done.
After restarting ComfyUI, please refresh the browser.
FETCH DATA from: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1514988643_custom-node-list.json
FETCH DATA from: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1742899825_extension-node-map.json

still gets after restarting and refresh

**Comment by kijai** [comment]
You need to find the actual import error from the startup log to know what's causing this, if you can't find it then share the whole log here and I can take a look.

**Comment by Pindang2** [comment]
Hi, I'm experiencing same issue:

```
C:\Users\Pindang2\Documents\_TEMP\_AI\ComfyUI_windows_portable>run_nvidia_gpu.bat

C:\Users\Pindang2\Documents\_TEMP\_AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 16376 MB, total RAM 65310 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Users\Pindang2\Documents\_TEMP\_AI\ComfyUI_windows_portable\ComfyUI\web
Total VRAM 16376 MB, total RAM 65310 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
C:\Users\Pindang2\Documents\_TEMP\_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-segment-anything-2\sam2\modeling\sam\transformer.py:20: UserWarning: Flash Attention is disabled as it requires a GPU with Ampere (8.0) CUDA capability.
  OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = get_sdpa_settings()
Traceback (most recent call last):
  File "C:\Users\Pindang2\Documents\_TEMP\_AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Pindang2\Documents\_TEMP\_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\__init__.py", line 1, in <module>
    from .nodes import SUPIR_Upscale
  File "C:\Users\Pindang2\Documents\_TEMP\_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\nodes.py", line 4, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'

Cannot import C:\Users\Pindang2\Documents\_TEMP\_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR module for custom nodes: No module named 'omegaconf'
[VideoHelperSuite] - WARNING - Failed to import imageio_ffmpeg

Import times for custom nodes:
   0.0 seconds: C:\Users\Pindang2\Documents\_TEMP\_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): C:\Users\Pindang2\Documents\_TEMP\_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR
   0.0 seconds: C:\Users\Pindang2\Documents\_TEMP\_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-segment-anything-2
   0.0 seconds: C:\Users\Pindang2\Documents\_TEMP\_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: C:\Users\Pindang2\Documents\_TEMP\_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

I tried `python_embeded\python.exe -m pip install --upgrade omegaconf`, It was successful.
If I see the Omegaconf package installed and still get the same issue, what should I do?
