### ISSUE TITLE
(IMPORT FAILED): /mnt/wf/ComfyUI/custom_nodes/ComfyUI-SUPIR

### ISSUE THREAD

**Issue by mike-rowley** [kijai/ComfyUI-SUPIR#119]
I am getting an Import Failed on loading the comfy server, I didnt find anything that appeared to match from current or past issues.

I have tried to fix Supir, uninstalled and reinstalled it, I reran pip install -r requirements.txt and updated comfy to the latest and it still fails to load.
Any suggestions?

Here is the traceback:

### ComfyUI Revision: 2169 [0fecfd2b] | Released on '2024-05-09'
Traceback (most recent call last):
  File "/mnt/wf/ComfyUI/nodes.py", line 1867, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/wf/ComfyUI/custom_nodes/ComfyUI-SUPIR/__init__.py", line 1, in <module>
    from .nodes import SUPIR_Upscale
  File "/mnt/wf/ComfyUI/custom_nodes/ComfyUI-SUPIR/nodes.py", line 11, in <module>
    from .sgm.util import instantiate_from_config
  File "/mnt/wf/ComfyUI/custom_nodes/ComfyUI-SUPIR/sgm/__init__.py", line 1, in <module>
    from .models import AutoencodingEngine, DiffusionEngine
  File "/mnt/wf/ComfyUI/custom_nodes/ComfyUI-SUPIR/sgm/models/__init__.py", line 1, in <module>
    from .autoencoder import AutoencodingEngine
  File "/mnt/wf/ComfyUI/custom_nodes/ComfyUI-SUPIR/sgm/models/autoencoder.py", line 6, in <module>
    import pytorch_lightning as pl
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 27, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 26, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/callback.py", line 22, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/pytorch_lightning/utilities/types.py", line 41, in <module>
    from torchmetrics import Metric
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/torchmetrics/__init__.py", line 22, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/torchmetrics/functional/audio/pit.py", line 22, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/torchmetrics/utilities/__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/torchmetrics/metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/torchmetrics/utilities/data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _TORCH_GREATER_EQUAL_1_13, _XLA_AVAILABLE
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/torchmetrics/utilities/imports.py", line 51, in <module>
    _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/lightning_utilities/core/imports.py", line 77, in compare_version
    pkg = importlib.import_module(package)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import (  # noqa: F401
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/torchaudio/_extension/__init__.py", line 45, in <module>
    _load_lib("libtorchaudio")
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 64, in _load_lib
    torch.ops.load_library(path)
  File "/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/torch/_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN2at4_ops10zeros_like4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEENS6_INS5_12MemoryFormatEEE

Cannot import /mnt/wf/ComfyUI/custom_nodes/ComfyUI-SUPIR module for custom nodes: /mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN2at4_ops10zeros_like4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEENS6_INS5_12MemoryFormatEEE

**Comment by kijai** [comment]
Something about pytorch-lightning, possible you have some other node that uses older version.. I'm not forcing a version as it can lead to such issues with other nodes, you could check if you have pytorch-lightning>=2.2.1 at least, and force install the specific version that is known to work: `pip install pytorch-lightning==2.2.1`

What torch version are you running?

**Comment by mike-rowley** [comment]
I ran the lightning pip command and everything is updated to 2.2.1 and I get the same error loading the comfy server

Pytorch version is '2.3.0+cu121'

**Comment by kijai** [comment]
> I ran the lightning pip command and everything is updated to 2.2.1 and I get the same error loading the comfy server
> 
> Pytorch version is '2.3.0+cu121'
> 
> Thanks for the assistance in sorting this out 🙏

Just checking, did you run the command in the python virtual environment of your install? As in activated it first with the venv/Scripts/Activate

**Comment by mike-rowley** [comment]
Yes I ran the pip command in the env for comfy

**Comment by mike-rowley** [comment]
I was able to resolve my issue from this post https://github.com/pytorch/audio/issues/62

pip install -U torch torchaudio --no-cache-dir

Apparently the -U is the important fix, after this command and a ComfyUI restart, Supir loads again.
