### ISSUE TITLE
(IMPORT FAILED): /home/runner/ComfyUI/custom_nodes/ComfyUI-SUPIR

### ISSUE THREAD

**Issue by the2ndface** [kijai/ComfyUI-SUPIR#120]
The installation was successful in the cloud environment, but the loading failed.
`Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-SUPIR/__init__.py", line 1, in <module>
    from .nodes import SUPIR_Upscale
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-SUPIR/nodes.py", line 11, in <module>
    from .sgm.util import instantiate_from_config
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-SUPIR/sgm/__init__.py", line 1, in <module>
    from .models import AutoencodingEngine, DiffusionEngine
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-SUPIR/sgm/models/__init__.py", line 1, in <module>
    from .autoencoder import AutoencodingEngine
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-SUPIR/sgm/models/autoencoder.py", line 6, in <module>
    import pytorch_lightning as pl
  File "/home/runner/.local/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 27, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/runner/.local/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/home/runner/.local/lib/python3.10/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 26, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/home/runner/.local/lib/python3.10/site-packages/pytorch_lightning/callbacks/callback.py", line 22, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/runner/.local/lib/python3.10/site-packages/pytorch_lightning/utilities/types.py", line 41, in <module>
    from torchmetrics import Metric
  File "/home/runner/.local/lib/python3.10/site-packages/torchmetrics/__init__.py", line 18, in <module>
    import pretty_errors  # noqa: F401
  File "/home/runner/.local/lib/python3.10/site-packages/pretty_errors/__init__.py", line 4, in <module>
    terminal_is_interactive = sys.stderr.isatty()
AttributeError: 'ComfyUIManagerLogger' object has no attribute 'isatty'

Cannot import /home/runner/ComfyUI/custom_nodes/ComfyUI-SUPIR module for custom nodes: 'ComfyUIManagerLogger' object has no attribute 'isatty'`

**Comment by msunx** [comment]
same error

**Comment by kijai** [comment]
I'm not sure if this has anything to do with these nodes, the Manager is having some updates and issues currently.

**Comment by msunx** [comment]
same problem

**Comment by Autantpourmoi** [comment]
same pb

**Comment by sunkinux** [comment]
> File "/home/runner/.local/lib/python3.10/site-packages/pretty_errors/**init**.py", line 4, 

find your pretty_errors/__init__.py, the error log shows the path, 

rewrite the code

# terminal_is_interactive = sys.stderr.isatty()
terminal_is_interactive = None
if sys.stderr is not None and hasattr(sys.stderr, "isatty"):
    terminal_is_interactive = sys.stderr.isatty()
