### ISSUE TITLE
controlnet with supir possible?

### ISSUE THREAD

**Issue by KingsmanZer0** [kijai/ComfyUI-SUPIR#123]
hi trying to use controlnet with supir so i can increase the control scale while keeping similar composition but im not sure how i would connect it. im able to do controlnet with a regular img2img workflow on confyui but not sure how i would connect it with supir.
i used the latent add node to add the image from canny then combined it with the supir encoder  then both combined to the supir sampler but i get this error:
"!!! Exception during processing!!! Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Traceback (most recent call last):
  File "C:\Users\Tuan Do\Desktop\ComfyUI - TEST\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuan Do\Desktop\ComfyUI - TEST\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuan Do\Desktop\ComfyUI - TEST\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuan Do\Desktop\ComfyUI - TEST\ComfyUI\comfy_extras\nodes_latent.py", line 27, in op
    samples_out["samples"] = s1 + s2
![Screenshot 2024-05-20 002408](https://github.com/kijai/ComfyUI-SUPIR/assets/93020987/d98e36b6-5e13-4c19-951f-21be712728ad)
![Screenshot 2024-05-20 003006](https://github.com/kijai/ComfyUI-SUPIR/assets/93020987/f329e7c6-f690-44b9-a718-12cffde6b2f4)

**Comment by kijai** [comment]
SUPIR is currently only implemented as it's own pipeline, we can't add other controlnets to it currently.
