### ISSUE TITLE
TypeError: string indices must be integers, not 'str'   Для продолжения нажмите любую клавишу . . .

### ISSUE THREAD

**Issue by fememystic** [kijai/ComfyUI-SUPIR#130]
`data_path:  D:\_AI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\data #read_workflow_json_files_all D:\_AI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\app\ /mixlab/folder_paths False 'llamafile' /mixlab/folder_paths False 'llamafile' got prompt [rgthree] Using rgthree's optimized recursive execution. [rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute. [rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI. Diffusion using fp16 Diffusion using bf16 Encoder using bf16 Using non-tiled sampling making attention of type 'vanilla-xformers' with 512 in_channels building MemoryEfficientAttnBlock with 512 in_channels... Working with z of shape (1, 4, 32, 32) = 4096 dimensions. making attention of type 'vanilla-xformers' with 512 in_channels building MemoryEfficientAttnBlock with 512 in_channels... Attempting to load SUPIR model: [D:\_AI\ComfyUI\models\checkpoints\SUPIR-v0F.ckpt] Loaded state_dict from [D:\_AI\ComfyUI\models\checkpoints\SUPIR-v0F.ckpt] Attempting to load SDXL model: [D:\_AI\ComfyUI\models\checkpoints\realvisxlV30_v30Bakedvae.safetensors]  D:\_AI>pause For continuation press any key...`

After launching SUPIR v1 in my favorite workflow i found that the workflow doesn't work anymore. Have no idea why, because i use it almost since it was launched and had no problems. Nothing was rly changed after that but maybe i'm missing something, Tried to press "update all" in manager, didn't help... What can i do?

**Comment by fememystic** [comment]
[SUPIR (no moondream).json](https://github.com/kijai/ComfyUI-SUPIR/files/15428947/SUPIR.no.moondream.json)
This is the workflow

**Comment by fememystic** [comment]
If you need all the CMD error from the moment of launching the bat file until i press the que promt button
```
"D:\_AI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-24 09:56:23.321889
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: D:\_AI\python_embeded\python.exe
** Log path: D:\_AI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\rgthree-comfy
   0.2 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 32512 MB
pytorch version: 2.2.0+cu121
xformers version: 0.0.25
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Error:
[WinError 1314] Клиент не обладает требуемыми правами: 'D:\\_AI\\ComfyUI\\custom_nodes\\ComfyLiterals\\js' -> 'D:\\_AI\\ComfyUI\\web\\extensions\\ComfyLiterals'
Failed to create symlink to D:\_AI\ComfyUI\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: D:\_AI\ComfyUI\custom_nodes\ComfyLiterals\js
Target: D:\_AI\ComfyUI\web\extensions\ComfyLiterals
[AnimateDiff] - WARNING - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.
[AnimateDiff] - ERROR - No models available. Please download one and put it in models folder
Adding D:\_AI\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from D:\_AI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from D:\_AI\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from D:\_AI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Loaded AnimateDiff from D:\_AI\ComfyUI\custom_nodes\comfyui-animatediff\animatediff/sliding_schedule.py
Loaded IPAdapter nodes from D:\_AI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from D:\_AI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V5.5.11)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.5)
### Loading: ComfyUI-Impact-Pack (V5.5.11)
Loaded ImpactPack nodes from D:\_AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.Traceback (most recent call last):
  File "D:\_AI\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\_AI\\ComfyUI\\custom_nodes\\ComfyUI-CLIPSeg-main\\__init__.py'


Cannot import D:\_AI\ComfyUI\custom_nodes\ComfyUI-CLIPSeg-main module for custom nodes: [Errno 2] No such file or directory: 'D:\\_AI\\ComfyUI\\custom_nodes\\ComfyUI-CLIPSeg-main\\__init__.py'
[Crystools INFO] Crystools version: 1.12.0
[Crystools INFO] CPU: AMD Ryzen 5 7500F 6-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3090
[Crystools INFO] NVIDIA Driver: 551.78
[Moondream] trying to update model versions...ok
[Moondream] found model versions: 2024-03-04, 2024-03-06, 2024-03-13, 2024-04-02, 2024-05-08, 2024-05-20
Total VRAM 24576 MB, total RAM 32512 MB
pytorch version: 2.2.0+cu121
xformers version: 0.0.25
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
### Loading: ComfyUI-Impact-Pack (V5.5.11)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V0.71)
### Loading: ComfyUI-Manager (V2.34.1)
### ComfyUI Revision: 2204 [b02bcced] | Released on '2024-05-23'
#fix sys.stdout.isatty
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
ffmpeg could not be found. Using ffmpeg from imageio-ffmpeg.
--------------
 ### Mixlab Nodes: Loaded
## lama torchscript model not found: D:\_AI\ComfyUI\models\lama\big-lama.pt,pls download from https://github.com/enesmsahin/simple-lama-inpainting/releases/download/v0.1.0/big-lama.pt
LaMaInpainting.available True
## clip_interrogator_model not found: D:\_AI\ComfyUI\models\clip_interrogator\Salesforce/blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## text_generator_model not found: D:\_AI\ComfyUI\models\prompt_generator\text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: D:\_AI\ComfyUI\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
 --------------
------------------------------------------
### N-Suite Revision: ab4af9de
Current version of packaging: 23.2
Version of cpuinfo: Not found
Current version of git: 3.1.41
Current version of moviepy: 1.0.3
Current version of cv2: 4.7.0
Current version of skbuild: 0.17.6
Version of typing: Not found
Current version of diskcache: 5.6.3
Current version of llama_cpp: 0.2.26+cu121
Current version of timm: 0.9.16
Traceback (most recent call last):
  File "D:\_AI\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\_AI\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 10, in <module>
    from .inference_ootd import OOTDiffusion
  File "D:\_AI\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\inference_ootd.py", line 23, in <module>
    from .pipelines_ootd.pipeline_ootd import OotdPipeline
  File "D:\_AI\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\pipeline_ootd.py", line 27, in <module>
    from .unet_vton_2d_condition import UNetVton2DConditionModel
  File "D:\_AI\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\unet_vton_2d_condition.py", line 23, in <module>
    from .unet_vton_2d_blocks import (
  File "D:\_AI\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\unet_vton_2d_blocks.py", line 23, in <module>
    from .transformer_vton_2d import Transformer2DModel
  File "D:\_AI\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\transformer_vton_2d.py", line 29, in <module>
    from diffusers.models.embeddings import CaptionProjection, PatchEmbed
ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' (D:\_AI\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)

Cannot import D:\_AI\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion module for custom nodes: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' (D:\_AI\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)
_PS_ All packages are installed.
_PS_ backend_path D:\_AI\ComfyUI\custom_nodes\comfyui-photoshop\Backend.py
_PS_ Backend Started
_PS_ Photoshop plugin didn't install! Please install it first.
_PS_ Photoshop plugin didn't install! Please install it first.
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: D:\_AI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
[ReActor] - STATUS - Running v0.5.0-b3 in ComfyUI
Torch version: 2.2.0+cu121
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider

From Bmad Custom Nodes
 Loaded 122 nodes:
  + api nodes (14)
  + simple utility nodes (58)
  + CV nodes (49)
  + color clip ade20k node (1)
 Not loaded:
  * extension dependent nodes
 Problems:
  ! No module named 'custom_nodes.ComfyUI_ADV_CLIP_emb'

------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
FizzleDorf Custom Nodes: Loaded
[tinyterraNodes] Loaded
ИНФОРМАЦИЯ: не удается найти файлы по заданным шаблонам.
Traceback (most recent call last):
  File "D:\_AI\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\_AI\ComfyUI\custom_nodes\human-parser-comfyui-node\__init__.py", line 1, in <module>
    from .HumanParserLIPCustomNode import HumanParserLIPCustomNode
  File "D:\_AI\ComfyUI\custom_nodes\human-parser-comfyui-node\HumanParserLIPCustomNode.py", line 5, in <module>
    from .utils import generate
  File "D:\_AI\ComfyUI\custom_nodes\human-parser-comfyui-node\utils.py", line 8, in <module>
    from .schp import networks
  File "D:\_AI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\networks\__init__.py", line 3, in <module>
    from .AugmentCE2P import resnet101
  File "D:\_AI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\networks\AugmentCE2P.py", line 21, in <module>
    from ..modules import InPlaceABNSync
  File "D:\_AI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "D:\_AI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\bn.py", line 10, in <module>
    from .functions import *
  File "D:\_AI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\functions.py", line 12, in <module>
    _backend = load(name="inplace_abn",
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_AI\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "D:\_AI\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\_AI\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "D:\_AI\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2238, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "D:\_AI\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2373, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 466, in check_output
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

Cannot import D:\_AI\ComfyUI\custom_nodes\human-parser-comfyui-node module for custom nodes: Command '['where', 'cl']' returned non-zero exit status 1.

[rgthree] Loaded 39 magnificent nodes.
[rgthree] Will use rgthree's optimized recursive execution.

Searge-SDXL v4.3.1 in D:\_AI\ComfyUI\custom_nodes\SeargeSDXL
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `D:\_AI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 212 nodes successfully.

        "Art is the lie that enables us to realize the truth." - Pablo Picasso


Import times for custom nodes:
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-Crystools-save
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\image-resize-comfyui
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\comfyui_ab_samplercustom
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUi_PromptStylers
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds (IMPORT FAILED): D:\_AI\ComfyUI\custom_nodes\ComfyUI-CLIPSeg-main
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\Comfyui-StableSR
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\Comfyui-SAL-VTON
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-Video-Matting
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-IC-Light
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds (IMPORT FAILED): D:\_AI\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\facerestore_cf
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\comfyui-dream-project
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\comfyui_bmad_nodes
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-Flowty-LDSR
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\comfyui-reactor-node
   0.0 seconds: D:\_AI\ComfyUI\custom_nodes\comfyui_segment_anything
   0.2 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-InstantID
   0.2 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-N-Nodes
   0.2 seconds (IMPORT FAILED): D:\_AI\ComfyUI\custom_nodes\human-parser-comfyui-node
   0.2 seconds: D:\_AI\ComfyUI\custom_nodes\clipseg.py
   0.3 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: D:\_AI\ComfyUI\custom_nodes\SeargeSDXL
   0.4 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-SUPIR
   0.5 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-Hangover-Moondream
   0.6 seconds: D:\_AI\ComfyUI\custom_nodes\comfyui-art-venture
   0.9 seconds: D:\_AI\ComfyUI\custom_nodes\comfyui-photoshop
   1.1 seconds: D:\_AI\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.3 seconds: D:\_AI\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   2.5 seconds: D:\_AI\ComfyUI\custom_nodes\ComfyUI-Crystools

https_key OK:  D:\_AI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\https\certificate.crt D:\_AI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\https\private.key




Starting server
To see the GUI go to: http://127.0.0.1:8188
To see the GUI go to: https://127.0.0.1:8189
FETCH DATA from: D:\_AI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
WARNING path D:\_AI\ComfyUI\models\checkpoints\CHEYENNE_v16VAEBaked.safetensors exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints CHEYENNE_v16VAEBaked.safetensors
WARNING path D:\_AI\ComfyUI\models\checkpoints\Deliberate-inpainting.safetensors exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints Deliberate-inpainting.safetensors
WARNING path D:\_AI\ComfyUI\models\checkpoints\Deliberate_v1-inpainting.safetensors exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints Deliberate_v1-inpainting.safetensors
WARNING path D:\_AI\ComfyUI\models\checkpoints\Deliberate_v1.1-inpainting.safetensors exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints Deliberate_v1.1-inpainting.safetensors
WARNING path D:\_AI\ComfyUI\models\checkpoints\Deliberate_v2-inpainting.safetensors exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints Deliberate_v2-inpainting.safetensors
WARNING path D:\_AI\ComfyUI\models\checkpoints\Deliberate_v2.safetensors exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints Deliberate_v2.safetensors
WARNING path D:\_AI\ComfyUI\models\checkpoints\ip-adapter-faceid-plusv2_sd15.bin exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints ip-adapter-faceid-plusv2_sd15.bin
WARNING path D:\_AI\ComfyUI\models\checkpoints\ip-adapter-faceid-plusv2_sdxl_lora.safetensors exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints ip-adapter-faceid-plusv2_sdxl_lora.safetensors
WARNING path D:\_AI\ComfyUI\models\checkpoints\ip-adapter-faceid-portrait-v11_sd15.bin exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints ip-adapter-faceid-portrait-v11_sd15.bin
[ERROR] An error occurred while retrieving information for the 'CheckpointLoader|pysssss' node.
Traceback (most recent call last):
  File "D:\_AI\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\_AI\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_AI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\better_combos.py", line 119, in INPUT_TYPES
    populate_items(names, "checkpoints")
  File "D:\_AI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\better_combos.py", line 98, in populate_items
    names.sort(key=lambda i: i["content"].lower())
  File "D:\_AI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\better_combos.py", line 98, in <lambda>
    names.sort(key=lambda i: i["content"].lower())
                             ~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

Error: OpenAI API key is invalid OpenAI features wont work for you
QualityOfLifeSuit_Omar92::NSP ready
WARNING path D:\_AI\ComfyUI\models\checkpoints\CHEYENNE_v16VAEBaked.safetensors exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints CHEYENNE_v16VAEBaked.safetensors
WARNING path D:\_AI\ComfyUI\models\checkpoints\Deliberate-inpainting.safetensors exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints Deliberate-inpainting.safetensors
WARNING path D:\_AI\ComfyUI\models\checkpoints\Deliberate_v1-inpainting.safetensors exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints Deliberate_v1-inpainting.safetensors
WARNING path D:\_AI\ComfyUI\models\checkpoints\Deliberate_v1.1-inpainting.safetensors exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints Deliberate_v1.1-inpainting.safetensors
WARNING path D:\_AI\ComfyUI\models\checkpoints\Deliberate_v2-inpainting.safetensors exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints Deliberate_v2-inpainting.safetensors
WARNING path D:\_AI\ComfyUI\models\checkpoints\Deliberate_v2.safetensors exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints Deliberate_v2.safetensors
WARNING path D:\_AI\ComfyUI\models\checkpoints\ip-adapter-faceid-plusv2_sd15.bin exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints ip-adapter-faceid-plusv2_sd15.bin
WARNING path D:\_AI\ComfyUI\models\checkpoints\ip-adapter-faceid-plusv2_sdxl_lora.safetensors exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints ip-adapter-faceid-plusv2_sdxl_lora.safetensors
WARNING path D:\_AI\ComfyUI\models\checkpoints\ip-adapter-faceid-portrait-v11_sd15.bin exists but doesn't link anywhere, skipping.
(pysssss:better_combos) Unable to get path for checkpoints ip-adapter-faceid-portrait-v11_sd15.bin
[ERROR] An error occurred while retrieving information for the 'CheckpointLoader|pysssss' node.
Traceback (most recent call last):
  File "D:\_AI\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\_AI\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_AI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\better_combos.py", line 119, in INPUT_TYPES
    populate_items(names, "checkpoints")
  File "D:\_AI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\better_combos.py", line 98, in populate_items
    names.sort(key=lambda i: i["content"].lower())
  File "D:\_AI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\better_combos.py", line 98, in <lambda>
    names.sort(key=lambda i: i["content"].lower())
                             ~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

data_path:  D:\_AI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\data
#read_workflow_json_files_all D:\_AI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\app\"
```

**Comment by kijai** [comment]
There are a lot of various errors/warnings regarding other custom nodes, none of them are about SUPIR though, including the error in the title. It's pretty hard to say what's the cause for it not working with all that going on, I'd suggest trying on a cleaner install.
