### ISSUE TITLE
Can it run on pytorch2.4+cuda12.4?

### ISSUE THREAD

**Issue by ultimatech-cn** [kijai/ComfyUI-SUPIR#160]
File "/comfyui/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/comfyui/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/comfyui/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/comfyui/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/comfyui/custom_nodes/ComfyUI-KJNodes/nodes/image_nodes.py", line 121, in colormatch
    out = torch.stack(out, dim=0).to(torch.float32)
          ^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2-17-gcd49553
- **Arguments:** /comfyui/main.py --disable-auto-launch --disable-metadata --enable-cors-header * --listen 0.0.0.0
- **OS:** posix
- **Python Version:** 3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA RTX A4000 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 16883908608
  - **VRAM Free:** 16384755490
  - **Torch VRAM Total:** 369098752
  - **Torch VRAM Free:** 121931554

## Logs
```
2024-09-09 15:51:28,585 - root - INFO - Total VRAM 16102 MB, total RAM 257563 MB
2024-09-09 15:51:28,585 - root - INFO - pytorch version: 2.4.1+cu121
2024-09-09 15:51:28,586 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-09 15:51:28,586 - root - INFO - Device: cuda:0 NVIDIA RTX A4000 : cudaMallocAsync
2024-09-09 15:51:29,433 - root - INFO - Using pytorch cross attention
2024-09-09 15:51:30,576 - root - INFO - [Prompt Server] web root: /comfyui/web
2024-09-09 15:51:30,577 - root - INFO - Adding extra search path checkpoints /runpod-volume/models/checkpoints/
2024-09-09 15:51:30,577 - root - INFO - Adding extra search path clip /runpod-volume/models/clip/
2024-09-09 15:51:30,578 - root - INFO - Adding extra search path clip_vision /runpod-volume/models/clip_vision/
2024-09-09 15:51:30,578 - root - INFO - Adding extra search path configs /runpod-volume/models/configs/
2024-09-09 15:51:30,578 - root - INFO - Adding extra search path controlnet /runpod-volume/models/controlnet/
2024-09-09 15:51:30,578 - root - INFO - Adding extra search path embeddings /runpod-volume/models/embeddings/
2024-09-09 15:51:30,578 - root - INFO - Adding extra search path loras /runpod-volume/models/loras/
2024-09-09 15:51:30,578 - root - INFO - Adding extra search path upscale_models /runpod-volume/models/upscale_models/
2024-09-09 15:51:30,578 - root - INFO - Adding extra search path vae /runpod-volume/models/vae/
2024-09-09 15:51:31,051 - root - INFO - Total VRAM 16102 MB, total RAM 257563 MB
2024-09-09 15:51:31,051 - root - INFO - pytorch version: 2.4.1+cu121
2024-09-09 15:51:31,051 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-09 15:51:31,051 - root - INFO - Device: cuda:0 NVIDIA RTX A4000 : cudaMallocAsync
2024-09-09 15:51:31,520 - matplotlib.font_manager - INFO - generated new fontManager
2024-09-09 15:51:32,359 - root - INFO - 
Import times for custom nodes:
2024-09-09 15:51:32,359 - root - INFO -    0.0 seconds: /comfyui/custom_nodes/websocket_image_save.py
2024-09-09 15:51:32,359 - root - INFO -    0.1 seconds: /comfyui/custom_nodes/ComfyUI-Manager
2024-09-09 15:51:32,359 - root - INFO -    0.1 seconds: /comfyui/custom_nodes/ComfyUI-KJNodes
2024-09-09 15:51:32,359 - root - INFO -    1.2 seconds: /comfyui/custom_nodes/ComfyUI-SUPIR
2024-09-09 15:51:32,359 - root - INFO - 
2024-09-09 15:51:32,363 - root - INFO - Starting server

2024-09-09 15:51:32,363 - root - INFO - To see the GUI go to: http://0.0.0.0:8188
2024-09-09 15:52:10,739 - root - INFO - got prompt
2024-09-09 15:52:10,977 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-09-09 15:52:10,981 - root - INFO - model_type EPS
2024-09-09 15:52:14,033 - root - INFO - Using pytorch attention in VAE
2024-09-09 15:52:14,034 - root - INFO - Using pytorch attention in VAE
2024-09-09 15:52:16,848 - root - INFO - Requested to load SDXL
2024-09-09 15:52:16,848 - root - INFO - Loading 1 new model
2024-09-09 15:52:17,486 - root - INFO - loaded completely 0.0 4897.0483474731445 True
2024-09-09 15:52:36,125 - root - INFO - Requested to load SDXLClipModel
2024-09-09 15:52:36,125 - root - INFO - Loading 1 new model
2024-09-09 15:52:36,351 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-09-09 15:54:03,768 - root - INFO - Prompt executed in 113.02 seconds
2024-09-09 15:54:59,004 - root - INFO - got prompt
2024-09-09 15:55:00,344 - root - INFO - Requested to load SDXL
2024-09-09 15:55:00,345 - root - INFO - Loading 1 new model
2024-09-09 15:55:00,949 - root - INFO - loaded completely 0.0 4897.0483474731445 True
2024-09-09 15:55:08,925 - root - INFO - Requested to load SDXLClipModel
2024-09-09 15:55:08,926 - root - INFO - Loading 1 new model
2024-09-09 15:55:09,136 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-09-09 15:56:26,194 - root - ERROR - !!! Exception during processing !!! stack expects a non-empty TensorList
2024-09-09 15:56:26,195 - root - ERROR - Traceback (most recent call last):
  File "/comfyui/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/comfyui/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/comfyui/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/comfyui/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/comfyui/custom_nodes/ComfyUI-KJNodes/nodes/image_nodes.py", line 121, in colormatch
    out = torch.stack(out, dim=0).to(torch.float32)
          ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: stack expects a non-empty TensorList

2024-09-09 15:56:26,196 - root - INFO - Prompt executed in 87.19 seconds
```

**Comment by ultimatech-cn** [comment]
Choosing wrong checkpoint.
