### ISSUE TITLE
requirement installed, but...

### ISSUE THREAD

**Issue by ffdown** [kijai/ComfyUI-SUPIR#2]
```
Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\nodes.py", line 11, in <module>
    from .sgm.util import instantiate_from_config
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\sgm\__init__.py", line 1, in <module>
    from .models import AutoencodingEngine, DiffusionEngine
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\sgm\models\__init__.py", line 1, in <module>
    from .autoencoder import AutoencodingEngine
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\sgm\models\autoencoder.py", line 6, in <module>
    import pytorch_lightning as pl
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pytorch_lightning\__init__.py", line 27, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 26, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pytorch_lightning\callbacks\callback.py", line 22, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pytorch_lightning\utilities\__init__.py", line 18, in <module>
    from lightning_fabric.utilities import (
ImportError: cannot import name 'measure_flops' from 'lightning_fabric.utilities' (E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\lightning_fabric\utilities\__init__.py)

Cannot import E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR module for custom nodes: cannot import name 'measure_flops' from 'lightning_fabric.utilities' (E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\lightning_fabric\utilities\__init__.py)
```

**Comment by kijai** [comment]
The current requirements worked for me in a fresh portable install, from the error it seems like it's pytorch-lightning version related, it should be: pytorch-lightning==2.1.2
manual install, run this in ComfyUI_windows_portable -folder:
`python_embeded\python.exe -m pip install pytorch-lightning==2.1.2`

**Comment by 602387193c** [comment]
请问工作流在哪里啊？
