### ISSUE TITLE
Issues running with 16gb of vram (oom)

### ISSUE THREAD

**Issue by Joly0** [kijai/ComfyUI-SUPIR#41]
Hey guys, when trying to run this in a more or less simple workflow, the processing stops while loading the models with an OOM error:
```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/config/05-comfy-ui/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/config/05-comfy-ui/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/config/05-comfy-ui/ComfyUI/custom_nodes/ComfyUI-0246/utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "/config/05-comfy-ui/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/config/05-comfy-ui/ComfyUI/custom_nodes/ComfyUI-SUPIR/nodes.py", line 212, in process
    self.model.init_tile_vae(encoder_tile_size=encoder_tile_size_pixels, decoder_tile_size=decoder_tile_size_latent)
AttributeError: 'SUPIR_Upscale' object has no attribute 'model'

Failed to move model to device
Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 15.44 GiB
Requested               : 4.50 MiB
Device limit            : 15.70 GiB
Free (according to CUDA): 20.94 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB
Prompt executed in 38.67 seconds
```

This is using a 4060ti with 16gb of vram.

Here is also the workflow if someone is interested.
[Simple-Supir_wFaceDetailer.json](https://github.com/kijai/ComfyUI-SUPIR/files/14515535/Simple-Supir_wFaceDetailer.json)

I tried it with different resolutions for the image and even went down to 265x265 without a difference

**Comment by kijai** [comment]
Probably the initial model takes too much memory before SUPIR node, as this is only a wrapper node it doesn't utilize comfy memory management. You can try running Comfy with --disable-smart-memory to stop it from keeping models on GPU.

**Comment by Joly0** [comment]
Tried that, but still same:
```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/config/05-comfy-ui/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/config/05-comfy-ui/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/config/05-comfy-ui/ComfyUI/custom_nodes/ComfyUI-0246/utils.py", line 381, in new_func
Failed to move model to device    res_value = old_func(*final_args, **kwargs)
  File "/config/05-comfy-ui/ComfyUI/execution.py", line 75, in map_node_over_list

    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/config/05-comfy-ui/ComfyUI/custom_nodes/ComfyUI-SUPIR/nodes.py", line 212, in process
    self.model.init_tile_vae(encoder_tile_size=encoder_tile_size_pixels, decoder_tile_size=decoder_tile_size_latent)
AttributeError: 'SUPIR_Upscale' object has no attribute 'model'

Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 15.44 GiB
Requested               : 4.50 MiB
Device limit            : 15.70 GiB
Free (according to CUDA): 20.94 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB
Prompt executed in 218.67 seconds
```

**Comment by kijai** [comment]
Added some unloading and at least for me with similar workflow now the memory is freed before this node, and for example 1024 to 2048 works with under 16GB:
![image](https://github.com/kijai/ComfyUI-SUPIR/assets/40791699/b33aceb0-2975-4ce0-9246-3b5347779977)

**Comment by Joly0** [comment]
Yep, that helped alot. With 1024x1024 i never go above 65% vram usage. Nice :)
