### ISSUE TITLE
When loading the graph, the following node types were not found: SUPIR_Upscale

### ISSUE THREAD

**Issue by paulerbear** [kijai/ComfyUI-SUPIR#46]
I have cloned the repository to my comfui/custom_nodes folder but when loading a workflow file containing the SUPIR_Upscaler node (https://comfyworkflows.com/workflows/b703fa8b-5fe0-4678-8692-021766a891c4) I am greeted with the following error: 

![Screenshot 2024-03-08 105316](https://github.com/kijai/ComfyUI-SUPIR/assets/145676927/24ba605e-e5bb-4399-af59-795de452155e)

**Comment by kijai** [comment]
You also need to install the requirements.txt. Refer to the readme for general instructions.

**Comment by paulerbear** [comment]
Thank you for your response Kijai. I use ComfyUI_windows_portable and so I ran "python_embeded\python.exe -m pip install -r ComfyUI\custom_nodes\ComfyUI-SUPIR\requirements.txt" in the ComfyUI_windows_portable -folder per the readme.md 
Shell reported that requirements already satisfied.
![image](https://github.com/kijai/ComfyUI-SUPIR/assets/145676927/23bc585e-f6eb-4a6c-a4a6-b7377eb4e7ed)
Unfortunately, the error persists
![image](https://github.com/kijai/ComfyUI-SUPIR/assets/145676927/e4078abc-aff3-49cd-9fc4-cfdecbaf9990)

**Comment by kijai** [comment]
Look for an import error in the startup log, or give me the full startup log here.

**Comment by paulerbear** [comment]
Import times for custom nodes:
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\canvas_tab
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hangover-Moondream
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.0 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.3 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.5 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.7 seconds (IMPORT FAILED): A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR
   0.7 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-moondream
   0.8 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.6 seconds: A:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

**Comment by kijai** [comment]
That just shows there there is an import error, not the actual error, it's much earlier in the log somewhere.

**Comment by jszewczyk** [comment]
I have the same error:

Torch version: 2.6.0+cu126
Traceback (most recent call last):
  File "C:\Users\info\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2113, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\info\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\__init__.py", line 1, in <module>
    from .nodes import SUPIR_Upscale
  File "C:\Users\info\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\nodes.py", line 11, in <module>
    from .sgm.util import instantiate_from_config
  File "C:\Users\info\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\sgm\__init__.py", line 1, in <module>
    from .models import AutoencodingEngine, DiffusionEngine
  File "C:\Users\info\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\sgm\models\__init__.py", line 1, in <module>
    from .autoencoder import AutoencodingEngine
  File "C:\Users\info\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\sgm\models\autoencoder.py", line 6, in <module>
    import pytorch_lightning as pl
  File "C:\Users\info\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pytorch_lightning\__init__.py", line 6, in <module>
    from lightning_utilities import module_available
  File "C:\Users\info\ComfyUI_windows_portable\python_embeded\Lib\site-packages\lightning_utilities\__init__.py", line 6, in <module>
    from lightning_utilities.core.apply_func import apply_to_collection
  File "C:\Users\info\ComfyUI_windows_portable\python_embeded\Lib\site-packages\lightning_utilities\core\__init__.py", line 4, in <module>
    from lightning_utilities.core.imports import compare_version, module_available
  File "C:\Users\info\ComfyUI_windows_portable\python_embeded\Lib\site-packages\lightning_utilities\core\imports.py", line 14, in <module>
    import pkg_resources
  File "C:\Users\info\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

Cannot import C:\Users\info\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR module for custom nodes: module 'pkgutil' has no attribute 'ImpImporter'
C:\Users\info\ComfyUI_windows_portable
############################################
C:\Users\info\ComfyUI_windows_portable\custom_nodes\ComfyUI-NAI-styler\CSV
############################################
[]
############################################
