### ISSUE TITLE
Import Failed, help.

### ISSUE THREAD

**Issue by K-O-N-B** [kijai/ComfyUI-SUPIR#62]
Traceback (most recent call last):
  File "H:\ComfyUI-qiuye\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI-SUPIR\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI-SUPIR\nodes.py", line 11, in <module>
    from .sgm.util import instantiate_from_config
  File "H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI-SUPIR\sgm\__init__.py", line 1, in <module>
    from .models import AutoencodingEngine, DiffusionEngine
  File "H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI-SUPIR\sgm\models\__init__.py", line 1, in <module>
    from .autoencoder import AutoencodingEngine
  File "H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI-SUPIR\sgm\models\autoencoder.py", line 6, in <module>
    import pytorch_lightning as pl
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\pytorch_lightning\__init__.py", line 28, in <module>
    from pytorch_lightning import metrics  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\pytorch_lightning\metrics\__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\pytorch_lightning\metrics\classification\__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\pytorch_lightning\metrics\classification\accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.functional.accuracy import _accuracy_compute, _accuracy_update
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\pytorch_lightning\metrics\functional\__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.functional.accuracy import accuracy  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\pytorch_lightning\metrics\functional\accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.classification.helpers import _input_format_classification, DataType
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\pytorch_lightning\metrics\classification\helpers.py", line 19, in <module>
    from pytorch_lightning.metrics.utils import select_topk, to_onehot
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\pytorch_lightning\metrics\utils.py", line 18, in <module>
    from pytorch_lightning.utilities import rank_zero_warn
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\pytorch_lightning\utilities\__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 25, in <module>
    from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_AVAILABLE
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\pytorch_lightning\utilities\imports.py", line 76, in <module>
    _HYDRA_EXPERIMENTAL_AVAILABLE = _module_available("hydra.experimental")
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\pytorch_lightning\utilities\imports.py", line 35, in _module_available
    return find_spec(module_path) is not None
           ^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 94, in find_spec
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\hydra\__init__.py", line 5, in <module>
    from hydra import utils
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\hydra\utils.py", line 8, in <module>
    import hydra._internal.instantiate._instantiate2
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 11, in <module>
    from hydra._internal.utils import _locate
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\hydra\_internal\utils.py", line 17, in <module>
    from hydra.core.utils import get_valid_filename, validate_config_path
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\hydra\core\utils.py", line 19, in <module>
    from hydra.core.hydra_config import HydraConfig
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\hydra\core\hydra_config.py", line 6, in <module>
    from hydra.conf import HydraConf
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\hydra\conf\__init__.py", line 45, in <module>
    class JobConf:
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\hydra\conf\__init__.py", line 70, in JobConf
    @dataclass
     ^^^^^^^^^
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'hydra.conf.JobConf.JobConfig.OverrideDirname'> for field override_dirname is not allowed: use default_factory

Cannot import H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI-SUPIR module for custom nodes: mutable default <class 'hydra.conf.JobConf.JobConfig.OverrideDirname'> for field override_dirname is not allowed: use default_factory

**Comment by kijai** [comment]
Something going wrong with pytorch-lightning, the specific version that definitely works is defined in the requirements.txt, how did you install this exactly?

**Comment by K-O-N-B** [comment]
> Something going wrong with pytorch-lightning, the specific version that definitely works is defined in the requirements.txt, how did you install this exactly?

I am just a  newbie, don't know how the pytorch and requirements.txt work.... T_T

just download other youtube's comfyui package

**Comment by kijai** [comment]
The node is in the ComfyUI-Manager now, installing it from there would also take care of the requirements.

**Comment by K-O-N-B** [comment]
install from Manager, but still import failed.....

**Comment by kijai** [comment]
Never seen that specific error so this is a tough one, would need to know python version used and other details about your python environment.

**Comment by K-O-N-B** [comment]
> Never seen that specific error so this is a tough one, would need to know python version used and other details about your python environment.

[Diagnostics-1710770146.log](https://github.com/kijai/ComfyUI-SUPIR/files/14637242/Diagnostics-1710770146.log)
here is my log files, helpful for solving the problem?
