### ISSUE TITLE
Why the new version has not the same quality of the First Supir version?

### ISSUE THREAD

**Issue by ronaldomirandah** [kijai/ComfyUI-SUPIR#65]
I have made this before the update
![FIRST](https://github.com/kijai/ComfyUI-SUPIR/assets/12447907/e4871edd-c164-4038-96e9-1474cfce8a5c)

After the update, is not the same quality as before, it changes too much the original. Is something i am missing?

![last](https://github.com/kijai/ComfyUI-SUPIR/assets/12447907/79f9c143-c151-433d-a563-a3ec3001cfd3)

**Comment by kijai** [comment]
Need bit more info, what settings, original image dimensions? From just looking at the images I'd say you should lower the cfg values a bit.

**Comment by ronaldomirandah** [comment]
> Need bit more info, what settings, original image dimensions? From just looking at the images I'd say you should lower the cfg values a bit.

I always used the default settings from the first version. The image size is 700 x 672 (but never had a problem before with any image size or aspect ratio)

Is there a way to get the first version? I overwritted with this last one :((((

Thanks a lot for your work and time!

**Comment by kijai** [comment]
Are you simply comparing old defaults vs new defaults? If so then it's just matter of matching the settings.

**Comment by ronaldomirandah** [comment]
> Are you simply comparing old defaults vs new defaults? If so then it's just matter of matching the settings.

Have you any idea how to match the Supir 2.0 with the previous one? I realised the old one cfg scale start was 0, with this it comes with cfg scale start at 40.  And the CFG on the previous one was 7.5, with this new one, comes at 4.  Just that for now seems different...

**Comment by kijai** [comment]
If you are talking about the very first version, it had a bug (same bug as in the original SUPIR) that made the cfg min scale 4.0 always. I wouldn't worry about trying to match it exactly, you can try setting cfg to 4.0 and cfg min to 7.5, and also other way around to see if you get the results you want.

**Comment by ronaldomirandah** [comment]
thanks a lot for your time and efforts man! Please, is there a way to the previous release? I forget to back up, so its gone in my HD :(

**Comment by kijai** [comment]
I really don't think there's any need to go back, there's nothing that has changed so much that you can't get similar results currently, for example using the new v2 nodes I tried with your image:

https://github.com/kijai/ComfyUI-SUPIR/assets/40791699/6bf1c552-3116-4e70-827d-f220ec127f56

workflow:
[supir_v2_example_02.json](https://github.com/kijai/ComfyUI-SUPIR/files/14629360/supir_v2_example_02.json)

**Comment by EddieGithub26** [comment]
I'm getting an error when running that workflow:
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\nodes_v2.py", line 562, in condition
    return ({"cond": c, "original_size":latents["original_size"]}, {"uncond": uc},)
                                        ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'original_size'

**Comment by ronaldomirandah** [comment]
> I really don't think there's any need to go back, there's nothing that has changed so much that you can't get similar results currently, for example using the new v2 nodes I tried with your image:
> 
>  explorer_z0Xqo7H0up.mp4 
> workflow: [supir_v2_example_02.json](https://github.com/kijai/ComfyUI-SUPIR/files/14629360/supir_v2_example_02.json)

thanks, for your time man. Really appreciated!
I am back to version, cause i am getting memory errors with the v2. Not really errors, it eats more VRAM then the v1. I cant upscale 1k to 2k. With version 1  i could. Even using that 8 something trick i cant! :(

**Comment by kijai** [comment]
> > I really don't think there's any need to go back, there's nothing that has changed so much that you can't get similar results currently, for example using the new v2 nodes I tried with your image:
> > explorer_z0Xqo7H0up.mp4
> > workflow: [supir_v2_example_02.json](https://github.com/kijai/ComfyUI-SUPIR/files/14629360/supir_v2_example_02.json)
> 
> thanks, for your time man. Really appreciated! I am back to version 1, cause i am getting memory errors with the v2. Not really errors, it eats more VRAM then the v1. I cant upscale 1k to 2k. With version 1 i could. Even using that 8 something trick i cant! :(

With tiled_vae on? How much VRAM do you have? There shouldn't be differences in memory use overall, at least I haven't noticed any, tested now and it's using bit under 10GB with fp8 when doing 2048x2048

**Comment by kijai** [comment]
> I'm getting an error when running that workflow: !!! Exception during processing !!! Traceback (most recent call last): File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\nodes_v2.py", line 562, in condition return ({"cond": c, "original_size":latents["original_size"]}, {"uncond": uc},) ~~~~~~~^^^^^^^^^^^^^^^^^ KeyError: 'original_size'

This was caused by my new update where I didn't take into account taking the latent from the encode node instead of first stage node to the conditioner. It's now fixed with latest version.

**Comment by ronaldomirandah** [comment]
> > > I really don't think there's any need to go back, there's nothing that has changed so much that you can't get similar results currently, for example using the new v2 nodes I tried with your image:
> > > explorer_z0Xqo7H0up.mp4
> > > workflow: [supir_v2_example_02.json](https://github.com/kijai/ComfyUI-SUPIR/files/14629360/supir_v2_example_02.json)
> > 
> > 
> > thanks, for your time man. Really appreciated! I am back to version 1, cause i am getting memory errors with the v2. Not really errors, it eats more VRAM then the v1. I cant upscale 1k to 2k. With version 1 i could. Even using that 8 something trick i cant! :(
> 
> With tiled_vae on? How much VRAM do you have? There shouldn't be differences in memory use overall, at least I haven't noticed any, tested now and it's using bit under 10GB with fp8 when doing 2048x2048

Wow thanks for the tip. With vae on, i was able to double scale a 1.400 image. Was nice! With the workflow you shared was more confused. I did that using just the main node. Need to try more now. Got a better impression now :)))

**Comment by ronaldomirandah** [comment]
Byt the way, turning VAE ON, is there any degradation or less quality?

**Comment by kijai** [comment]
> Byt the way, turning VAE ON, is there any degradation or less quality?

Not really anything noticeable, it's just a lot slower.

**Comment by simartem** [comment]
> ample using the new v2 nodes I tried with your image:

Do CFG values in the sampler node is supposed to be related, to the main checkpoint (for example Juggernaut v8) ?
For example i normally use CFG 5 or 6 when generating. Should it be 5 or 6 in the SUPIR sampler ? Or this CFG relates to the Supir model ?

**Comment by kijai** [comment]
> > ample using the new v2 nodes I tried with your image:
> 
> Do CFG values in the sampler node is supposed to be related, to the main checkpoint (for example Juggernaut v8) ? For example i normally use CFG 5 or 6 when generating. Should it be 5 or 6 in the SUPIR sampler ? Or this CFG relates to the Supir model ?

It really depends what you want, there is no single answer for this, higher CFG will change it more from the original. The original defaults were using the linear scaling too, start 7.5 end 4.0 for fidelity and start 4.0 end 1.0 for quality. Personally I just adjust them as needed.
