### ISSUE TITLE
KeyError: 'text_projection'

### ISSUE THREAD

**Issue by shiyuleixia** [kijai/ComfyUI-SUPIR#81]
How to solve this problem
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/data/aigc/ComfyUI/custom_nodes/ComfyUI-SUPIR/nodes.py", line 291, in process
    clip_g = build_text_model_from_openai_state_dict(sd, cast_dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/aigc/ComfyUI/custom_nodes/ComfyUI-SUPIR/nodes.py", line 52, in build_text_model_from_openai_state_dict
    embed_dim = state_dict["text_projection"].shape[1]
                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'text_projection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/aigc/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/aigc/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/aigc/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/aigc/ComfyUI/custom_nodes/ComfyUI-SUPIR/nodes.py", line 294, in process
    raise Exception("Failed to load second clip model from SDXL checkpoint")
Exception: Failed to load second clip model from SDXL checkpoint

Prompt executed in 5.02 seconds

**Comment by kijai** [comment]
Which SDXL checkpoint do you have selected?

**Comment by JozeeLin** [comment]
I get the same error. use PixelWaveTurbo sdxl-turbo model.[https://openart.ai/workflows/8e4EWBCHyEeCIFJxn2JV](url) . this is my workflow.

**Comment by JozeeLin** [comment]
I got the same error. using "PixelWaveTurbo" sdxl-turbo model. [https://openart.ai/workflows/8e4EWBCHyEeCIFJxn2JV](https://github.com/kijai/ComfyUI-SUPIR/issues/url) . this is my workflow.

**Comment by JozeeLin** [comment]
maybe your setting is fault. on the "SUPIR Upscale (Legacy)" node , "sdxl model" was not set correctly.

**Comment by mklwolf** [comment]
Same error by using supir_model_loader_v2_clip, even I using example workflow and create v2 loader clip, It didn't work. So, I only able to using supir_model_loader V2 (no clip). the sdxl checkpoint is "LEOSAM's HelloWorld XL 7.0".
----------------------------------------------------------------------------------------------------------------------
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Loading weights to:  cpu
Diffusion using fp16
Using XFORMERS
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Attempting to load SDXL model from node inputs
Requested to load SDXL
loaded partially 4516.594157028198 4516.5930252075195 0
Loading first clip model from SDXL checkpoint
Requested to load SD1ClipModel
loaded completely 923.2329509735107 235.84423828125 True
Loading second clip model from SDXL checkpoint
Requested to load SD1ClipModel
loaded completely 1037.0493534088134 235.84423828125 True
!!! Exception during processing !!! Failed to load second clip model from SDXL checkpoint
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\nodes_v2.py", line 1148, in process
    clip_g = build_text_model_from_openai_state_dict(clip_g_sd, device, cast_dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\nodes_v2.py", line 52, in build_text_model_from_openai_state_dict
    embed_dim = state_dict["text_projection"].shape[1]
                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'text_projection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 347, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 222, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 194, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 183, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\nodes_v2.py", line 1154, in process
    raise Exception("Failed to load second clip model from SDXL checkpoint")
Exception: Failed to load second clip model from SDXL checkpoint
